var invariant = require('./invariant');
var _ = require('underscore');

var cards = [
  {"age":1,"type":"victory","name":"Baths","players":3},
  {"age":1,"type":"victory","name":"Alter","players":3},
  {"age":1,"type":"victory","name":"Theater","players":3},
  {"age":1,"type":"economy","name":"East Trading Post","players":3},
  {"age":1,"type":"economy","name":"West Trading Post","players":3},
  {"age":1,"type":"economy","name":"Marketplace","players":3},
  {"age":1,"type":"military","name":"Stockade","players":3},
  {"age":1,"type":"military","name":"Barracks","players":3},
  {"age":1,"type":"military","name":"Guard Tower","players":3},
  {"age":1,"type":"science","name":"Apothecary","players":3},
  {"age":1,"type":"science","name":"Workshop","players":3},
  {"age":1,"type":"science","name":"Scriptorium","players":3},
  {"age":1,"type":"basic_resource","name":"Lumber Yard","players":3},
  {"age":1,"type":"basic_resource","name":"Stone Pit","players":3},
  {"age":1,"type":"basic_resource","name":"Clay Pool","players":3},
  {"age":1,"type":"basic_resource","name":"Ore Vein","players":3},
  {"age":1,"type":"basic_resource","name":"Clay Pit","players":3},
  {"age":1,"type":"basic_resource","name":"Timber Yard","players":3},
  {"age":1,"type":"advanced_resource","name":"Loom","players":3},
  {"age":1,"type":"advanced_resource","name":"Glassworks","players":3},
  {"age":1,"type":"advanced_resource","name":"Press","players":3},
  {"age":1,"type":"victory","name":"Pawnshop","players":4},
  {"age":1,"type":"economy","name":"Tavern","players":4},
  {"age":1,"type":"military","name":"Guard Tower","players":4},
  {"age":1,"type":"science","name":"Scriptorium","players":4},
  {"age":1,"type":"basic_resource","name":"Lumber Yard","players":4},
  {"age":1,"type":"basic_resource","name":"Ore Vein","players":4},
  {"age":1,"type":"basic_resource","name":"Excavation","players":4},
  {"age":1,"type":"victory","name":"Alter","players":5},
  {"age":1,"type":"economy","name":"Tavern","players":5},
  {"age":1,"type":"military","name":"Barracks","players":5},
  {"age":1,"type":"science","name":"Apothecary","players":5},
  {"age":1,"type":"basic_resource","name":"Stone Pit","players":5},
  {"age":1,"type":"basic_resource","name":"Clay Pool","players":5},
  {"age":1,"type":"basic_resource","name":"Forest Cave","players":5},
  {"age":1,"type":"victory","name":"Theater","players":6},
  {"age":1,"type":"economy","name":"Marketplace","players":6},
  {"age":1,"type":"basic_resource","name":"Tree Farm","players":6},
  {"age":1,"type":"basic_resource","name":"Mine","players":6},
  {"age":1,"type":"advanced_resource","name":"Loom","players":6},
  {"age":1,"type":"advanced_resource","name":"Glassworks","players":6},
  {"age":1,"type":"advanced_resource","name":"Press","players":6},
  {"age":1,"type":"victory","name":"Pawnshop","players":7},
  {"age":1,"type":"victory","name":"Baths","players":7},
  {"age":1,"type":"economy","name":"Tavern","players":7},
  {"age":1,"type":"economy","name":"East Trading Post","players":7},
  {"age":1,"type":"economy","name":"West Trading Post","players":7},
  {"age":1,"type":"military","name":"Stockade","players":7},
  {"age":1,"type":"science","name":"Workshop","players":7},

  {"age":2,"type":"victory","name":"Aquaduct","players":3},
  {"age":2,"type":"victory","name":"Temple","players":3},
  {"age":2,"type":"victory","name":"Statue","players":3},
  {"age":2,"type":"economy","name":"Forum","players":3},
  {"age":2,"type":"economy","name":"Caravensery","players":3},
  {"age":2,"type":"economy","name":"Vineyard","players":3},
  {"age":2,"type":"military","name":"Walls","players":3},
  {"age":2,"type":"military","name":"Stables","players":3},
  {"age":2,"type":"military","name":"Archery Range","players":3},
  {"age":2,"type":"victory","name":"Courthouse","players":3},
  {"age":2,"type":"science","name":"Dispensary","players":3},
  {"age":2,"type":"science","name":"Laboratory","players":3},
  {"age":2,"type":"science","name":"Library","players":3},
  {"age":2,"type":"science","name":"School","players":3},
  {"age":2,"type":"basic_resource","name":"Sawmill","players":3},
  {"age":2,"type":"basic_resource","name":"Quarry","players":3},
  {"age":2,"type":"basic_resource","name":"Brickyard","players":3},
  {"age":2,"type":"basic_resource","name":"Foundary","players":3},
  {"age":2,"type":"advanced_resource","name":"Loom","players":3},
  {"age":2,"type":"advanced_resource","name":"Glassworks","players":3},
  {"age":2,"type":"advanced_resource","name":"Press","players":3},
  {"age":2,"type":"economy","name":"Bazar","players":4},
  {"age":2,"type":"military","name":"Training Ground","players":4},
  {"age":2,"type":"science","name":"Dispensary","players":4},
  {"age":2,"type":"basic_resource","name":"Sawmill","players":4},
  {"age":2,"type":"basic_resource","name":"Quarry","players":4},
  {"age":2,"type":"basic_resource","name":"Brickyard","players":4},
  {"age":2,"type":"basic_resource","name":"Foundary","players":4},
  {"age":2,"type":"economy","name":"Caravensery","players":5},
  {"age":2,"type":"military","name":"Stables","players":5},
  {"age":2,"type":"victory","name":"Courthouse","players":5},
  {"age":2,"type":"science","name":"Laboratory","players":5},
  {"age":2,"type":"advanced_resource","name":"Loom","players":5},
  {"age":2,"type":"advanced_resource","name":"Glassworks","players":5},
  {"age":2,"type":"advanced_resource","name":"Press","players":5},
  {"age":2,"type":"victory","name":"Temple","players":6},
  {"age":2,"type":"economy","name":"Forum","players":6},
  {"age":2,"type":"economy","name":"Caravensery","players":6},
  {"age":2,"type":"economy","name":"Vineyard","players":6},
  {"age":2,"type":"military","name":"Training Ground","players":6},
  {"age":2,"type":"military","name":"Archery Range","players":6},
  {"age":2,"type":"science","name":"Library","players":6},
  {"age":2,"type":"victory","name":"Aquaduct","players":7},
  {"age":2,"type":"victory","name":"Statue","players":7},
  {"age":2,"type":"economy","name":"Forum","players":7},
  {"age":2,"type":"economy","name":"Bazar","players":7},
  {"age":2,"type":"military","name":"Walls","players":7},
  {"age":2,"type":"military","name":"Training Ground","players":7},
  {"age":2,"type":"science","name":"School","players":7},

  {"age":3,"type":"victory","name":"Pantheon","players":3},
  {"age":3,"type":"victory","name":"Gardens","players":3},
  {"age":3,"type":"victory","name":"Townhall","players":3},
  {"age":3,"type":"victory","name":"Palace","players":3},
  {"age":3,"type":"economy","name":"Haven","players":3},
  {"age":3,"type":"economy","name":"Lighthouse","players":3},
  {"age":3,"type":"military","name":"Fortificatins","players":3},
  {"age":3,"type":"military","name":"Arsenal","players":3},
  {"age":3,"type":"military","name":"Siege Workshop","players":3},
  {"age":3,"type":"economy","name":"Arena","players":3},
  {"age":3,"type":"victory","name":"Senate","players":3},
  {"age":3,"type":"science","name":"Lodge","players":3},
  {"age":3,"type":"science","name":"Observatory","players":3},
  {"age":3,"type":"science","name":"University","players":3},
  {"age":3,"type":"science","name":"Academy","players":3},
  {"age":3,"type":"science","name":"Study","players":3},
  {"age":3,"type":"victory","name":"Gardens","players":4},
  {"age":3,"type":"economy","name":"Haven","players":4},
  {"age":3,"type":"economy","name":"Chamber of Commerce","players":4},
  {"age":3,"type":"military","name":"Circus","players":4},
  {"age":3,"type":"military","name":"Arsenal","players":4},
  {"age":3,"type":"science","name":"University","players":4},
  {"age":3,"type":"victory","name":"Townhall","players":5},
  {"age":3,"type":"military","name":"Circus","players":5},
  {"age":3,"type":"military","name":"Siege Workshop","players":5},
  {"age":3,"type":"economy","name":"Arena","players":5},
  {"age":3,"type":"victory","name":"Senate","players":5},
  {"age":3,"type":"science","name":"Study","players":5},
  {"age":3,"type":"victory","name":"Pantheon","players":6},
  {"age":3,"type":"victory","name":"Townhall","players":6},
  {"age":3,"type":"economy","name":"Lighthouse","players":6},
  {"age":3,"type":"economy","name":"Chamber of Commerce","players":6},
  {"age":3,"type":"military","name":"Circus","players":6},
  {"age":3,"type":"science","name":"Lodge","players":6},
  {"age":3,"type":"victory","name":"Palace","players":7},
  {"age":3,"type":"military","name":"Fortificatins","players":7},
  {"age":3,"type":"military","name":"Arsenal","players":7},
  {"age":3,"type":"economy","name":"Arena","players":7},
  {"age":3,"type":"science","name":"Observatory","players":7},
  {"age":3,"type":"science","name":"Academy","players":7},

  {"age":"guild","type":"guild","name":"Workers Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Craftsmens Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Traders Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Philosophers Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Spies Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Stategists Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Shiowners Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Scientists Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Magistrates Guild","players":"N/A"},
  {"age":"guild","type":"guild","name":"Builders Guild","players":"N/A"}
];

// Returns a shuffled deck of cards for the given age
var deck_for_age = function(age, num_players) {
  invariant(age >= 1 && age <= 3, 'age must be 1, 2, or 3');

  var deck = _.filter(cards, function(card) {
    return card.age === age && card.players <= num_players;
  });
  // Special case guilds in the 3rd age
  if (age === 3) {
    var guilds = _.filter(cards, function(card) {
      return card.age === 'guild';
    });
    var guilds = _.sample(guilds, num_players + 2);
    deck = deck.concat(guilds);
  }

  invariant(deck.length === 7 * num_players, 'fucked up deck');
  return _.shuffle(deck);
}

exports.deck_for_age = deck_for_age;
exports.cards = cards;
