var cards = 
  [{"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Baths"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Alter"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Theater"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" East Trading Post"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" West Trading Post"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" Marketplace"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Stockade"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Barracks"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Guard Tower"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Apothecary"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Workshop"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Scriptorium"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Lumber Yard"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Stone Pit"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Clay Pool"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Ore Vein"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Clay Pit"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Timber Yard"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Loom"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Glassworks"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Press"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Pawnshop"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" Tavern"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Guard Tower"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Scriptorium"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Lumber Yard"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Ore Vein"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Excavation"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Alter"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" Tavern"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Barracks"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Apothecary"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Stone Pit"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Clay Pool"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Forest Cave"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Theater"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" Marketplace"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Tree Farm"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Raw Material"," Name":" Mine"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Loom"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Glassworks"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Manufactured Good"," Name":" Press"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Pawnshop"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Civilian Structure"," Name":" Baths"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" Tavern"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" East Trading Post"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Treasury Contents"," Name":" West Trading Post"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Military Structure"," Name":" Stockade"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" I"," Type":" Science Structure"," Name":" Workshop"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Aquaduct"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Temple"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Statue"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Forum"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Caravensery"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Vineyard"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Walls"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Stables"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Archery Range"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Courthouse"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Dispensary"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Laboratory"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Library"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" School"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Sawmill"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Quarry"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Brickyard"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Foundary"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Loom"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Glassworks"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Press"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Bazar"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Training Ground"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Dispensary"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Sawmill"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Quarry"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Brickyard"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Raw Material"," Name":" Foundary"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Caravensery"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Stables"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Courthouse"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Laboratory"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Loom"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Glassworks"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Manufactured Good"," Name":" Press"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Temple"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Forum"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Caravensery"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Vineyard"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Training Ground"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Archery Range"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" Library"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Aquaduct"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Civilian Structure"," Name":" Statue"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Forum"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Treasury Contents"," Name":" Bazar"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Walls"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Military Structure"," Name":" Training Ground"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" II"," Type":" Science Structure"," Name":" School"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Pantheon"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Gardens"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Townhall"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Palace"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Haven"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Lighthouse"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Fortificatins"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Arsenal"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Siege Workshop"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Arena"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Senate"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Lodge"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Observatory"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" University"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Academy"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Study"," Players":" 3+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Gardens"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Haven"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Chamber of Commerce"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Circus"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Arsenal"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" University"," Players":" 4+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Townhall"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Circus"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Siege Workshop"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Arena"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Senate"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Study"," Players":" 5+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Pantheon"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Townhall"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Lighthouse"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Chamber of Commerce"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Circus"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Lodge"," Players":" 6+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Civilian Structure"," Name":" Palace"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Fortificatins"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Military Structure"," Name":" Arsenal"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Treasury Contents"," Name":" Arena"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Observatory"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Science Structure"," Name":" Academy"," Players":" 7+","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Workers Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Craftsmens Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Traders Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Philosophers Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Spies Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Stategists Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Shiowners Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Scientists Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Magistrates Guild"," Players":" N/A","":null},
    {"Expansion":" N/A"," Age":" III"," Type":" Guild"," Name":" Builders Guild"," Players":" N/A","":null}]

var Game = function (num_players) {
  this.numPlayers = num_players;
  this.hands = [];
  this.age = 1;
};

Game.prototype.getAge = function() {
  return this.age;
}
